{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yirun",
    "module": "asmplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "asmplugin-1.0.0.jar",
          "url": "asmplugin-1.0.0.jar",
          "size": 15396,
          "sha512": "a08a926516f2cfd64e9a3837facefe7f7986daca0b04e984a532d5a77ed62a06b7e4aed528731de97bf444a4983e88f25250ca1a814dc10abf40c0d2cd57e67a",
          "sha256": "35935dd31d511c60549246bb3db2f957fc2f565b2296973d6de78877c97f23ec",
          "sha1": "3b61e190c1a7f4bdfe167a66fe6a1f34d7eab674",
          "md5": "0d3d18a445f532768157197090b26411"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "asmplugin-1.0.0.jar",
          "url": "asmplugin-1.0.0.jar",
          "size": 15396,
          "sha512": "a08a926516f2cfd64e9a3837facefe7f7986daca0b04e984a532d5a77ed62a06b7e4aed528731de97bf444a4983e88f25250ca1a814dc10abf40c0d2cd57e67a",
          "sha256": "35935dd31d511c60549246bb3db2f957fc2f565b2296973d6de78877c97f23ec",
          "sha1": "3b61e190c1a7f4bdfe167a66fe6a1f34d7eab674",
          "md5": "0d3d18a445f532768157197090b26411"
        }
      ]
    }
  ]
}
