{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yirun",
    "module": "asmplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "asmplugin-1.0.0.jar",
          "url": "asmplugin-1.0.0.jar",
          "size": 20798,
          "sha512": "bbdd1f51e99b232d67ee9a1245ea3cc62c6b4259ce409c45f2b90792a99b6a5716be709c4b704ced00150b1a2ad1a51390c683a69e5ae5a254fe659ed935b20b",
          "sha256": "196c4691535fbc71e7a1d74d20c947cdb1cc164cc626d3fec5e460db91bfa4f4",
          "sha1": "523e8b8511e2f6b079c726a33efe4314266ab67d",
          "md5": "c69d214326a02332cd74da216017f0ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "asmplugin-1.0.0.jar",
          "url": "asmplugin-1.0.0.jar",
          "size": 20798,
          "sha512": "bbdd1f51e99b232d67ee9a1245ea3cc62c6b4259ce409c45f2b90792a99b6a5716be709c4b704ced00150b1a2ad1a51390c683a69e5ae5a254fe659ed935b20b",
          "sha256": "196c4691535fbc71e7a1d74d20c947cdb1cc164cc626d3fec5e460db91bfa4f4",
          "sha1": "523e8b8511e2f6b079c726a33efe4314266ab67d",
          "md5": "c69d214326a02332cd74da216017f0ee"
        }
      ]
    }
  ]
}
