{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yirun",
    "module": "asmplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "asmplugin-1.0.0.jar",
          "url": "asmplugin-1.0.0.jar",
          "size": 11926,
          "sha512": "6fe359a88e20bbad7c0c82835953c97969226fa7bb854ae70ec826e5d3e025cfa3a8fd277abfdc06002e7fc3777d2daf9b9e1f3e343657c559afa9c101745b1e",
          "sha256": "ba0ca937f0e544e13078e4d8e5eb8fd5c8da8a9eddab5db6147decea72083ac5",
          "sha1": "734b36de0d77f2de83b73cc38e4b382f59c7eec2",
          "md5": "bebc89123f234a5c4c963b0aa77e08b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "asmplugin-1.0.0.jar",
          "url": "asmplugin-1.0.0.jar",
          "size": 11926,
          "sha512": "6fe359a88e20bbad7c0c82835953c97969226fa7bb854ae70ec826e5d3e025cfa3a8fd277abfdc06002e7fc3777d2daf9b9e1f3e343657c559afa9c101745b1e",
          "sha256": "ba0ca937f0e544e13078e4d8e5eb8fd5c8da8a9eddab5db6147decea72083ac5",
          "sha1": "734b36de0d77f2de83b73cc38e4b382f59c7eec2",
          "md5": "bebc89123f234a5c4c963b0aa77e08b4"
        }
      ]
    }
  ]
}
